import React, { useEffect, useMemo, useState } from 'react';
import { api } from '../../services/api';
import { Product } from '../../types';

interface PublicWebsiteViewProps { onOpenStaffApp?: () => void; }
/** Public V1: showcase and read-only digital menu only. */
export const PublicWebsiteView: React.FC<PublicWebsiteViewProps> = ({ onOpenStaffApp }) => {
  const [products, setProducts] = useState<Product[]>([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('all');
  useEffect(() => { api.getProducts().then(items => setProducts(items.filter(p => p.available))).catch(() => setProducts([])); }, []);
  const categories = useMemo(() => [...new Set(products.map(p => p.categoryId))], [products]);
  const menu = products.filter(p => (category === 'all' || p.categoryId === category) && `${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="min-h-screen bg-[#F7F7F5] text-[#252A27]"><header className="sticky top-0 bg-white border-b p-4 flex justify-between"><b>CAFÉ NOIR</b><nav className="space-x-4 text-sm"><a href="#accueil">Accueil</a><a href="#menu">Menu</a><a href="#concept">À propos</a><a href="#galerie">Galerie</a><a href="#contact">Contact</a></nav>{onOpenStaffApp && <button onClick={onOpenStaffApp}>Administration</button>}</header><main className="max-w-5xl mx-auto p-6 space-y-14"><section id="accueil"><h1 className="text-4xl font-serif font-bold">Café Noir</h1><p>Maison de café et de pâtisserie.</p></section><section id="menu"><h2 className="text-2xl font-bold">Menu digital</h2><p className="text-sm">Consultation uniquement — aucune commande ni aucun paiement en ligne.</p><div className="flex gap-2 my-4"><input aria-label="Rechercher dans le menu" value={query} onChange={e => setQuery(e.target.value)} placeholder="Rechercher" className="border p-2"/><select value={category} onChange={e => setCategory(e.target.value)} className="border p-2"><option value="all">Toutes catégories</option>{categories.map(c => <option key={c}>{c}</option>)}</select></div><div className="grid md:grid-cols-3 gap-4">{menu.map(p => <article key={p.id} className="bg-white border rounded p-4">{p.imageUrl && <img src={p.imageUrl} alt="" className="w-full h-32 object-cover rounded"/>}<h3 className="font-bold mt-2">{p.name}</h3><p className="text-sm">{p.description}</p><p className="font-bold mt-2">{p.price.toFixed(3)} DT</p>{p.options.length > 0 && <p className="text-xs">Variantes et suppléments disponibles</p>}</article>)}</div></section><section id="concept"><h2 className="text-2xl font-bold">À propos</h2><p>Notre concept et notre savoir-faire.</p></section><section id="galerie"><h2 className="text-2xl font-bold">Galerie</h2><p>Découvrez notre univers.</p></section><section id="contact"><h2 className="text-2xl font-bold">Contact & localisation</h2><p>18 Rue Saint-Dominique, Paris · +33 1 42 68 90 00</p></section></main></div>;
};
